import { Event, RegisteredUser } from "@/lib/types";

export const mockEvent: Event = {
  id: "evt-001",
  creatorId: "usr-101",
  slug: "tech-summit-2026",
  title: "Tech Summit 2026",
  description:
    "A premier technology conference bringing together industry leaders, developers, and innovators to discuss the latest trends in AI, cloud computing, and software engineering. Join us for keynotes, workshops, and networking sessions.",
  approvalStatus: "APPROVED",
  createdOn: "2026-02-15T10:00:00Z",
  startDatetime: "2026-04-10T09:00:00Z",
  endDatetime: "2026-04-12T18:00:00Z",
  imageData: "/placeholder-event.jpg",
  seats: 500,
  amount: 1500,
  visibility: "PUBLIC",
};

export const mockRegisteredUsers: RegisteredUser[] = [
  { id: "usr-201", email: "alice@example.com", approved: true },
  { id: "usr-202", email: "bob@example.com", approved: false },
  { id: "usr-203", email: "charlie@example.com", approved: true },
  { id: "usr-204", email: "diana@example.com", approved: false },
  { id: "usr-205", email: "eve@example.com", approved: true },
  { id: "usr-206", email: "frank@example.com", approved: false },
  { id: "usr-207", email: "grace@example.com", approved: true },
];

export const mockPrivateEvents: (Event & { 
  totalRegistrations: number; 
  seatsRemaining: number; 
  creator: { name: string; email: string } 
})[] = [
  {
    id: "pvt-evt-001",
    creatorId: "usr-101",
    slug: "annual-company-retreat-2026",
    title: "Annual Company Retreat",
    description: "Join us for a day of team building and strategic planning. Includes lunch, workshops, and evening social activities.",
    approvalStatus: "APPROVED",
    createdOn: "2026-02-01T08:00:00Z",
    startDatetime: "2026-04-15T09:00:00Z",
    endDatetime: "2026-04-15T18:00:00Z",
    imageData: "/placeholder-event.jpg",
    seats: 150,
    amount: 500,
    visibility: "INTERNAL",
    totalRegistrations: 120,
    seatsRemaining: 30,
    creator: { name: "John Smith", email: "john.smith@company.com" },
  },
  {
    id: "pvt-evt-002",
    creatorId: "usr-102",
    slug: "engineering-workshop-2026",
    title: "Engineering Best Practices Workshop",
    description: "Deep dive into our engineering standards, code review processes, and architectural patterns. Learn from senior engineers.",
    approvalStatus: "APPROVED",
    createdOn: "2026-02-05T10:30:00Z",
    startDatetime: "2026-04-20T14:00:00Z",
    endDatetime: "2026-04-20T17:00:00Z",
    imageData: "/placeholder-event.jpg",
    seats: 80,
    amount: 0,
    visibility: "INTERNAL",
    totalRegistrations: 65,
    seatsRemaining: 15,
    creator: { name: "Sarah Johnson", email: "sarah.j@company.com" },
  },
  {
    id: "pvt-evt-003",
    creatorId: "usr-103",
    slug: "leadership-summit-2026",
    title: "Leadership Development Summit",
    description: "Exclusive summit for management and team leads to discuss leadership strategies, mentoring, and team growth.",
    approvalStatus: "APPROVED",
    createdOn: "2026-02-08T09:15:00Z",
    startDatetime: "2026-05-01T10:00:00Z",
    endDatetime: "2026-05-02T16:00:00Z",
    imageData: "/placeholder-event.jpg",
    seats: 60,
    amount: 800,
    visibility: "INTERNAL",
    totalRegistrations: 45,
    seatsRemaining: 15,
    creator: { name: "Michael Chen", email: "m.chen@company.com" },
  },
  {
    id: "pvt-evt-004",
    creatorId: "usr-104",
    slug: "wellness-program-april",
    title: "Company Wellness Program",
    description: "Monthly wellness initiative featuring yoga sessions, health talks, and fitness challenges to promote employee well-being.",
    approvalStatus: "APPROVED",
    createdOn: "2026-02-10T11:00:00Z",
    startDatetime: "2026-04-25T08:00:00Z",
    endDatetime: "2026-04-25T09:30:00Z",
    imageData: "/placeholder-event.jpg",
    seats: 200,
    amount: 0,
    visibility: "INTERNAL",
    totalRegistrations: 180,
    seatsRemaining: 20,
    creator: { name: "Emily Rodriguez", email: "emily.r@company.com" },
  },
  {
    id: "pvt-evt-005",
    creatorId: "usr-105",
    slug: "product-roadmap-2026",
    title: "Product Roadmap Presentation",
    description: "Get insights into our product vision and roadmap for 2026. Understand upcoming features and strategic initiatives.",
    approvalStatus: "APPROVED",
    createdOn: "2026-02-12T14:30:00Z",
    startDatetime: "2026-04-22T15:00:00Z",
    endDatetime: "2026-04-22T16:30:00Z",
    imageData: "/placeholder-event.jpg",
    seats: 120,
    amount: 0,
    visibility: "INTERNAL",
    totalRegistrations: 95,
    seatsRemaining: 25,
    creator: { name: "David Park", email: "d.park@company.com" },
  },
  {
    id: "pvt-evt-006",
    creatorId: "usr-106",
    slug: "mentorship-program-launch",
    title: "Mentorship Program Launch",
    description: "Introducing our new mentorship program. Connect with experienced mentors and grow your career with personalized guidance.",
    approvalStatus: "APPROVED",
    createdOn: "2026-02-14T10:00:00Z",
    startDatetime: "2026-05-05T16:00:00Z",
    endDatetime: "2026-05-05T17:30:00Z",
    imageData: "/placeholder-event.jpg",
    seats: 100,
    amount: 250,
    visibility: "INTERNAL",
    totalRegistrations: 78,
    seatsRemaining: 22,
    creator: { name: "Lisa Anderson", email: "lisa.a@company.com" },
  },
];

