# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '876f8134-febe-4e80-9ab9-713bb6485171'
  imageRepository: 'project21frontend'
  containerRegistry: 'project21frontend.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  subscriptionId: $(subscriptionId)

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: project-21-backend-pool
    steps:
    - script: docker system prune -a -f

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(subscribtionId)
        KeyVaultName: 'project-21-key-vault'
        SecretsFilter: '*'

    - task: Docker@2
      displayName: Build image
      env:
        NEXT_PUBLIC_JWT_SECRET: $(NEXTPUBLICJWTSECRET)
        NEXT_PUBLIC_BACKEND_URL: $(NEXTPUBLICBACKENDURL)
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        arguments: -p 80:3000 --build-arg NEXT_PUBLIC_JWT_SECRET=$(NEXT_PUBLIC_JWT_SECRET) --build-arg NEXT_PUBLIC_BACKEND_URL=$(NEXT_PUBLIC_BACKEND_URL)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(0839a5ee-329a-4b35-82c1-7c70e55542eb)'
        appName: 'project-21-frontend'
        containers: 'project21frontend.azurecr.io/project21frontend:$(tag)'